os: linux
language: python
dist: focal

jobs:
  include:
    - python: 3.7-dev
    - python: 3.8-dev
    - python: 3.9-dev
    - python: nightly

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
